### sales user only route
### itemDescription2? is optional
### { message: string, status: number, item: item }
### Upload item
POST http://localhost:3000/item/item
Content-Type: multipart/form-data
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDExYjM2YjNlMTgwOGQ2NDZmOTgxMjAiLCJlbWFpbEFkZHJlc3MiOiJ2bXVlbEBnbWFsLmNvbSIsImFjY291bnRUeXBlIjoiVVNFUiIsImlhdCI6MTY3ODg4MTY5MH0.3hzqNbb63Ewfmi5kUZkQhq1DzlhWKYovj01a-9O5_RU

{
  "files": ["file1.files[0]", "file1.files[1]", "file1.files[2]"],
  "itemName": "my udnu",
  "price": 234,
  "itemDescription1": "e ojhh ah aa",
  "itemDescription2": "iuhf idhgi sahaoi d",
  "remainingCount": 23,
  "categories": ["a", "d"]
}

### sales user only route
### recive query param _id, itemName?, price?, itemDescription1?, itemDescription2?, remainingCount?, categories?
### { message: string, status: number, item: item }
### modify item
PATCH http://localhost:3000/item/item?_id=6413203ec12cb79c085bae3c&itemName=bbTest&categories=f,z
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDE0NWZkNWZlMzExOTg2NjEwZDY2NDIiLCJlbWFpbEFkZHJlc3MiOiJtbEBnbWFsLmNvbSIsImFjY291bnRUeXBlIjoiU0FMRVMiLCJpYXQiOjE2NzkwNTY5MzR9.koR_2YBxL1z0nzF0DtSQg8SudYi7COIMsUbiYaJy96s

### sales user only route
### takes param itemId
### delete item
DELETE http://localhost:3000/item/item/64137d894fb05a9c714f007d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDE0NWZkNWZlMzExOTg2NjEwZDY2NDIiLCJlbWFpbEFkZHJlc3MiOiJtbEBnbWFsLmNvbSIsImFjY291bnRUeXBlIjoiU0FMRVMiLCJpYXQiOjE2NzkwNTY5MzR9.koR_2YBxL1z0nzF0DtSQg8SudYi7COIMsUbiYaJy96s

### As body: itemId?, itemName?, category?
### As query: limit?, page?, topSelling?, limitedInStock?
### return { message: "" | string, status, data?: Item[], count? }
### get items
POST http://localhost:3000/item/items
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDE0ZDJiODMxZWNjYWZjOTAxMjMzN2UiLCJlbWFpbEFkZHJlc3MiOiJsYXRAZ21hbC5jb20iLCJhY2NvdW50VHlwZSI6IlVTRVIiLCJpYXQiOjE2NzkwODYyNzV9.sgbuNbr-3f-LeKmw-Qu9yGiptpF_c0IzI-UL8jTcBxA
Content-Type: application/json

{
  "category": "a"
}

### returns { message: "", categories: Category[], status?: number }
### query param: sortByReference?: true, limit?: number, count?: number
### Get categories
GET http://localhost:3000/item/categories?sortByReference=true&limit=2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDE1NjliMzBiOGQwZmZhMDQ1Njc4MTYiLCJlbWFpbEFkZHJlc3MiOiJsYXRAZ21hbC5jb20iLCJhY2NvdW50VHlwZSI6IlVTRVIiLCJpYXQiOjE2NzkxMjQ5MjB9.0qjNBBP17YvuSw_MB7e4r3ZI-B3TrP3rZwqCfhFEOC8