#User admin - create user
POST http://localhost:3000/user/user-admin/create-user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDExYjM2YjNlMTgwOGQ2NDZmOTgxMjAiLCJlbWFpbEFkZHJlc3MiOiJ2bXVlbEBnbWFsLmNvbSIsImFjY291bnRUeXBlIjoiVVNFUiIsImlhdCI6MTY3ODg4MTY5MH0.3hzqNbb63Ewfmi5kUZkQhq1DzlhWKYovj01a-9O5_RU
Content-Type: application/json

{
    "firstName": "Yusuf",
    "lastName": "Damola",
    "emailAddress": "an@emi.com",
    "password": "simplepass",
    "accountType": "USER"
}

### route to change user properties. Passed as query param, password passed in body.
### param:  firstName, lastName, emailAddress, password, address, contact, isBlocked
### modify user data
PATCH http://localhost:3000/user/user?lastName=Kareem
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDExYjM2YjNlMTgwOGQ2NDZmOTgxMjAiLCJlbWFpbEFkZHJlc3MiOiJ2bXVlbEBnbWFsLmNvbSIsImFjY291bnRUeXBlIjoiVVNFUiIsImlhdCI6MTY3ODg4MTY5MH0.3hzqNbb63Ewfmi5kUZkQhq1DzlhWKYovj01a-9O5_RU
Content-Type: application/json

{
    "password": "0000000"
}

### receive query param: firstName, lastName, address, contact, isBlocked, accountType, limit, skip
### returns { message: "", status: number, users: {}, count: number } 
### get users
GET http://localhost:3000/user/user-admin/users?limit=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDExYjM2YjNlMTgwOGQ2NDZmOTgxMjAiLCJlbWFpbEFkZHJlc3MiOiJ2bXVlbEBnbWFsLmNvbSIsImFjY291bnRUeXBlIjoiVVNFUiIsImlhdCI6MTY3ODg4MTY5MH0.3hzqNbb63Ewfmi5kUZkQhq1DzlhWKYovj01a-9O5_RU

### returns { message: "", status: number, user: {} } 
### get user data
GET http://localhost:3000/user/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDExYjM2YjNlMTgwOGQ2NDZmOTgxMjAiLCJlbWFpbEFkZHJlc3MiOiJ2bXVlbEBnbWFsLmNvbSIsImFjY291bnRUeXBlIjoiVVNFUiIsImlhdCI6MTY3ODg4MTY5MH0.3hzqNbb63Ewfmi5kUZkQhq1DzlhWKYovj01a-9O5_RU