### signup
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "firstName": "Yusuf",
    "lastName": "Olanrewaju",
    "emailAddress": "bu@gmail.com",
    "password": "123456789"
}

### signin
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "emailAddress": "bu@gmail.com",
    "password": "123456789"
}

### forgetPassword
GET http://localhost:3000/auth/send-password-reset-mail/vmuel@gmail.com

### resetPassword
POST http://localhost:3000/auth/reset-password/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbEFkZHJlc3MiOiJ2bXVlbEBnbWFpbC5jb20iLCJpYXQiOjE2Nzc2MDAzNzR9.ru9cxc0FZ1xCJ0PdKsfsC26NNLU8FKqL43lTSAlafbU
Content-Type: application/json

{
    "password": "0123456789"
}

### as query param: topBought?, limited?, limit?, page?, category?
### returns { message: "" | string, status: number, data?: Item[], count?: number }
### get items
GET http://localhost:3000/auth/item?category=men&topBought=true

### returns { message: "", categories: Category[], status?: number }
### query param: sortByReference?: true, limit?: number, count?: number
### Get categories
GET http://localhost:3000/auth/categories?sortByReference=true&limit=3