### signup
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "firstName": "Yusuf",
    "lastName": "Olanrewaju",
    "emailAddress": "vmuel@gmal.com",
    "password": "123456789"
}

### signin
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "emailAddress": "vmuel@gmal.com",
    "password": "0000000"
}

### forgetPassword
GET http://localhost:3000/auth/send-password-reset-mail/vmuel@gmail.com
Content-Type: application/json

### resetPassword
POST http://localhost:3000/auth/reset-password/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbEFkZHJlc3MiOiJ2bXVlbEBnbWFpbC5jb20iLCJpYXQiOjE2Nzc2MDAzNzR9.ru9cxc0FZ1xCJ0PdKsfsC26NNLU8FKqL43lTSAlafbU
Content-Type: application/json

{
    "password": "0123456789"
}